import { Html, Head, Main, NextScript } from 'next/document';


export default function Document() {
	return (
		<Html lang="ru">
			<Head>
			{/* Google Tag Manager */}
				<script async src={`https://www.googletagmanager.com/gtag/js?id=G-Y17V175XH8`} />
				<script
					dangerouslySetInnerHTML={{
						__html : 
						`
							window.dataLayer = window.dataLayer || [];
							function gtag(){dataLayer.push(arguments);}
							gtag('js', new Date());

							gtag('config', 'G-Y17V175XH8', {
								page_path: window.location.pathname,
							});
						`
					}}
				/>
				<title>web assist</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />

				{/* Google AdSense meta */}
				<meta name="google-adsense-account" content="ca-pub-7128744514279998" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<body>
				<Main />
				<NextScript />
			</body>
		</Html>
	);
}
