import { Html, Head, Main, NextScript } from 'next/document';


export default function Document() {
	return (
		<Html lang="ru">
			<Head>
			{/* Google Tag Manager */}
				<script async src={`https://www.googletagmanager.com/gtag/js?id=G-Y17V175XH8`} />
				<script
					dangerouslySetInnerHTML={{
						__html : 
						`
							window.dataLayer = window.dataLayer || [];
							function gtag(){dataLayer.push(arguments);}
							gtag('js', new Date());

							gtag('config', 'G-Y17V175XH8', {
								page_path: window.location.pathname,
							});
						`
					}}
				/>
				<script
					type='text/javascript'
					dangerouslySetInnerHTML={{
						__html : 
						`
							(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
							m[i].l=1*new Date();
							for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
							k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
							(window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
						
							ym(95034790, "init", {
								clickmap:true,
								trackLinks:true,
								accurateTrackBounce:true,
								webvisor:true
							});
						`
					}}
				/>
				<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7128744514279998" crossOrigin="anonymous"></script>
				<title>web assist</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />

				{/* Google AdSense meta */}
				<meta name="google-adsense-account" content="ca-pub-7128744514279998" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<body>
				<Main />
				<NextScript />
			</body>
		</Html>
	);
}
